export const cardTypes = [
  {
    internalCode: "explosion",
    name: "Exploding Kitten",
    effect: "You must play a Defuse card, or you explode!",
    imageUrl: "cards/chicken.png",
    isOpen: true,
  },
  {
    internalCode: "defuse",
    name: "Defuse",
    effect: "Defuse the Exploding Kitten",
    imageUrl: "cards/defuse-1.png",
    isOpen: true,
  },
  {
    internalCode: "attack",
    name: "Attack",
    effect: "End your turn and force the next player to take two turns.",
    imageUrl: "cards/attack-1.png",
    isOpen: true,
  },
  {
    internalCode: "skip",
    name: "Skip",
    effect: "Immediately end your turn without drawing a card.",
    imageUrl: "cards/skip-1.png",
    isOpen: true,
  },
  {
    internalCode: "favor",
    name: "Favor",
    effect: "Force another player to give you one of their cards.",
    imageUrl: "cards/favor-1.png",
    isOpen: true,
  },
  {
    internalCode: "shuffle",
    name: "Shuffle",
    effect: "Shuffle the draw pile.",
    imageUrl: "cards/shuffle-1.png",
    isOpen: true,
  },
  {
    internalCode: "future",
    name: "See the Future",
    effect: "Secretly peek at the top three cards in the draw pile.",
    imageUrl: "cards/seethefuture-1.png",
    isOpen: true,
  },
  {
    internalCode: "explosion",
    name: "Taco Cat",
    effect: "A palindrome. Play two to steal a random card.",
    imageUrl: "cards/randchick-1.png",
    isOpen: true,
  },
  {
    internalCode: "tacocat",
    name: "Cattermelon",
    effect: "Play two to steal a random card.",
    imageUrl: "cards/randchick-2.png",
    isOpen: true,
  },
  {
    internalCode: "cattermelon",
    name: "Hairy Potato Cat",
    effect: "Play two to steal a random card.",
    imageUrl: "cards/randchick-3.png",
    isOpen: true,
  },
  {
    internalCode: "hairypotatocat",
    name: "Beard Cat",
    effect: "Play two to steal a random card.",
    imageUrl: "cards/randchick-4.png",
    isOpen: true,
  },
];
