export const cardTypes = [
  {
    internalCode: 1,
    name: "explosion",
    effect: "You must play a Defuse card, or you explode!",
    imageUrl: "cards/chicken.png",
    isOpen: true,
  },
  {
    internalCode: 2,
    name: "defuse",
    effect: "Defuse the Exploding Kitten",
    imageUrl: "cards/defuse-1.png",
    isOpen: true,
  },
  {
    internalCode: 3,
    name: "attack",
    effect: "End your turn and force the next player to take two turns.",
    imageUrl: "cards/attack-1.png",
    isOpen: true,
  },
  {
    internalCode: 4,
    name: "skip",
    effect: "Immediately end your turn without drawing a card.",
    imageUrl: "cards/skip-1.png",
    isOpen: true,
  },
  {
    internalCode: 5,
    name: "favor",
    effect: "Force another player to give you one of their cards.",
    imageUrl: "cards/favor-1.png",
    isOpen: true,
  },
  {
    internalCode: 6,
    name: "shuffle",
    effect: "Shuffle the draw pile.",
    imageUrl: "cards/shuffle-1.png",
    isOpen: true,
  },
  {
    internalCode: 7,
    name: "future",
    effect: "Secretly peek at the top three cards in the draw pile.",
    imageUrl: "cards/seethefuture-1.png",
    isOpen: true,
  },
  {
    internalCode: 8,
    name: "hairypotatocat",
    effect: "Play two to have the same effect as a skip card.",
    imageUrl: "cards/randchick-1.png",
    isOpen: true,
  },
  {
    internalCode: 9,
    name: "tacocat",
    effect: "Play two to have the same effect as a future card.",
    imageUrl: "cards/randchick-2.png",
    isOpen: true,
  },
  {
    internalCode: 10,
    name: "cattermelon",
    effect: "Play two to have the same effect as a attack card.",
    imageUrl: "cards/randchick-3.png",
    isOpen: true,
  },
  {
    internalCode: 11,
    name: "beardcat",
    effect: "Play two to have the same effect as a shuffle card.",
    imageUrl: "cards/randchick-4.png",
    isOpen: true,
  },
  {
    internalCode: 12,
    name: "nope",
    effect: "Deny a move.",
    imageUrl: "cards/nope.png",
    isOpen: true,
  },
];
